replicaCount: 2
image:
  repository: kubefoundry/demo
  tag: "0.1.0"
  digest: ""
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 64Mi
