apiVersion: v1
kind: Namespace
metadata:
  name: fundamentos
  labels:
    kubefoundry.io/workload: 'true'
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.36
