apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: playground
  namespace: argocd
spec:
  description: Namespaced learning workloads only
  sourceRepos:
    - https://github.com/vynazevedo/kubefoundry.git
  destinations:
    - namespace: playground
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: NetworkPolicy
